version: '2'
services:
  #######################################
  # PHP application Docker container
  # Passwords in webdevops_docker/documentation/SERVICES.md
  # Default user, pass: root/dev dev
  #######################################
  app:
    build:
      context: ./webdevops_docker
      dockerfile: Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - /:/host_root
      - ./:/app/
      - ./_dev_dir/:/_dev_dir
      - ./webdevops_docker/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./webdevops_docker/:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - ./webdevops_docker/etc/environment.yml
      - ./webdevops_docker/etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025
